/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as V7RouteImport } from './routes/v7'
import { Route as V6RouteImport } from './routes/v6'
import { Route as V5RouteImport } from './routes/v5'
import { Route as V4RouteImport } from './routes/v4'
import { Route as V3RouteImport } from './routes/v3'
import { Route as V2RouteImport } from './routes/v2'
import { Route as V1RouteImport } from './routes/v1'
import { Route as IndexRouteImport } from './routes/index'

const V7IndexLazyRouteImport = createFileRoute('/v7/')()
const V6IndexLazyRouteImport = createFileRoute('/v6/')()
const V5IndexLazyRouteImport = createFileRoute('/v5/')()
const V4IndexLazyRouteImport = createFileRoute('/v4/')()
const V3IndexLazyRouteImport = createFileRoute('/v3/')()
const V2IndexLazyRouteImport = createFileRoute('/v2/')()
const V1IndexLazyRouteImport = createFileRoute('/v1/')()
const V7AppLazyRouteImport = createFileRoute('/v7/app')()
const V6AppLazyRouteImport = createFileRoute('/v6/app')()
const V5AppLazyRouteImport = createFileRoute('/v5/app')()
const V4AppLazyRouteImport = createFileRoute('/v4/app')()
const V3AppLazyRouteImport = createFileRoute('/v3/app')()
const V2AppLazyRouteImport = createFileRoute('/v2/app')()
const V1AppLazyRouteImport = createFileRoute('/v1/app')()

const V7Route = V7RouteImport.update({
  id: '/v7',
  path: '/v7',
  getParentRoute: () => rootRouteImport,
} as any)
const V6Route = V6RouteImport.update({
  id: '/v6',
  path: '/v6',
  getParentRoute: () => rootRouteImport,
} as any)
const V5Route = V5RouteImport.update({
  id: '/v5',
  path: '/v5',
  getParentRoute: () => rootRouteImport,
} as any)
const V4Route = V4RouteImport.update({
  id: '/v4',
  path: '/v4',
  getParentRoute: () => rootRouteImport,
} as any)
const V3Route = V3RouteImport.update({
  id: '/v3',
  path: '/v3',
  getParentRoute: () => rootRouteImport,
} as any)
const V2Route = V2RouteImport.update({
  id: '/v2',
  path: '/v2',
  getParentRoute: () => rootRouteImport,
} as any)
const V1Route = V1RouteImport.update({
  id: '/v1',
  path: '/v1',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const V7IndexLazyRoute = V7IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => V7Route,
} as any).lazy(() => import('./routes/v7/index.lazy').then((d) => d.Route))
const V6IndexLazyRoute = V6IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => V6Route,
} as any).lazy(() => import('./routes/v6/index.lazy').then((d) => d.Route))
const V5IndexLazyRoute = V5IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => V5Route,
} as any).lazy(() => import('./routes/v5/index.lazy').then((d) => d.Route))
const V4IndexLazyRoute = V4IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => V4Route,
} as any).lazy(() => import('./routes/v4/index.lazy').then((d) => d.Route))
const V3IndexLazyRoute = V3IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => V3Route,
} as any).lazy(() => import('./routes/v3/index.lazy').then((d) => d.Route))
const V2IndexLazyRoute = V2IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => V2Route,
} as any).lazy(() => import('./routes/v2/index.lazy').then((d) => d.Route))
const V1IndexLazyRoute = V1IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => V1Route,
} as any).lazy(() => import('./routes/v1/index.lazy').then((d) => d.Route))
const V7AppLazyRoute = V7AppLazyRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => V7Route,
} as any).lazy(() => import('./routes/v7/app.lazy').then((d) => d.Route))
const V6AppLazyRoute = V6AppLazyRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => V6Route,
} as any).lazy(() => import('./routes/v6/app.lazy').then((d) => d.Route))
const V5AppLazyRoute = V5AppLazyRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => V5Route,
} as any).lazy(() => import('./routes/v5/app.lazy').then((d) => d.Route))
const V4AppLazyRoute = V4AppLazyRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => V4Route,
} as any).lazy(() => import('./routes/v4/app.lazy').then((d) => d.Route))
const V3AppLazyRoute = V3AppLazyRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => V3Route,
} as any).lazy(() => import('./routes/v3/app.lazy').then((d) => d.Route))
const V2AppLazyRoute = V2AppLazyRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => V2Route,
} as any).lazy(() => import('./routes/v2/app.lazy').then((d) => d.Route))
const V1AppLazyRoute = V1AppLazyRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => V1Route,
} as any).lazy(() => import('./routes/v1/app.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/v1': typeof V1RouteWithChildren
  '/v2': typeof V2RouteWithChildren
  '/v3': typeof V3RouteWithChildren
  '/v4': typeof V4RouteWithChildren
  '/v5': typeof V5RouteWithChildren
  '/v6': typeof V6RouteWithChildren
  '/v7': typeof V7RouteWithChildren
  '/v1/app': typeof V1AppLazyRoute
  '/v2/app': typeof V2AppLazyRoute
  '/v3/app': typeof V3AppLazyRoute
  '/v4/app': typeof V4AppLazyRoute
  '/v5/app': typeof V5AppLazyRoute
  '/v6/app': typeof V6AppLazyRoute
  '/v7/app': typeof V7AppLazyRoute
  '/v1/': typeof V1IndexLazyRoute
  '/v2/': typeof V2IndexLazyRoute
  '/v3/': typeof V3IndexLazyRoute
  '/v4/': typeof V4IndexLazyRoute
  '/v5/': typeof V5IndexLazyRoute
  '/v6/': typeof V6IndexLazyRoute
  '/v7/': typeof V7IndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/v1/app': typeof V1AppLazyRoute
  '/v2/app': typeof V2AppLazyRoute
  '/v3/app': typeof V3AppLazyRoute
  '/v4/app': typeof V4AppLazyRoute
  '/v5/app': typeof V5AppLazyRoute
  '/v6/app': typeof V6AppLazyRoute
  '/v7/app': typeof V7AppLazyRoute
  '/v1': typeof V1IndexLazyRoute
  '/v2': typeof V2IndexLazyRoute
  '/v3': typeof V3IndexLazyRoute
  '/v4': typeof V4IndexLazyRoute
  '/v5': typeof V5IndexLazyRoute
  '/v6': typeof V6IndexLazyRoute
  '/v7': typeof V7IndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/v1': typeof V1RouteWithChildren
  '/v2': typeof V2RouteWithChildren
  '/v3': typeof V3RouteWithChildren
  '/v4': typeof V4RouteWithChildren
  '/v5': typeof V5RouteWithChildren
  '/v6': typeof V6RouteWithChildren
  '/v7': typeof V7RouteWithChildren
  '/v1/app': typeof V1AppLazyRoute
  '/v2/app': typeof V2AppLazyRoute
  '/v3/app': typeof V3AppLazyRoute
  '/v4/app': typeof V4AppLazyRoute
  '/v5/app': typeof V5AppLazyRoute
  '/v6/app': typeof V6AppLazyRoute
  '/v7/app': typeof V7AppLazyRoute
  '/v1/': typeof V1IndexLazyRoute
  '/v2/': typeof V2IndexLazyRoute
  '/v3/': typeof V3IndexLazyRoute
  '/v4/': typeof V4IndexLazyRoute
  '/v5/': typeof V5IndexLazyRoute
  '/v6/': typeof V6IndexLazyRoute
  '/v7/': typeof V7IndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/v1'
    | '/v2'
    | '/v3'
    | '/v4'
    | '/v5'
    | '/v6'
    | '/v7'
    | '/v1/app'
    | '/v2/app'
    | '/v3/app'
    | '/v4/app'
    | '/v5/app'
    | '/v6/app'
    | '/v7/app'
    | '/v1/'
    | '/v2/'
    | '/v3/'
    | '/v4/'
    | '/v5/'
    | '/v6/'
    | '/v7/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/v1/app'
    | '/v2/app'
    | '/v3/app'
    | '/v4/app'
    | '/v5/app'
    | '/v6/app'
    | '/v7/app'
    | '/v1'
    | '/v2'
    | '/v3'
    | '/v4'
    | '/v5'
    | '/v6'
    | '/v7'
  id:
    | '__root__'
    | '/'
    | '/v1'
    | '/v2'
    | '/v3'
    | '/v4'
    | '/v5'
    | '/v6'
    | '/v7'
    | '/v1/app'
    | '/v2/app'
    | '/v3/app'
    | '/v4/app'
    | '/v5/app'
    | '/v6/app'
    | '/v7/app'
    | '/v1/'
    | '/v2/'
    | '/v3/'
    | '/v4/'
    | '/v5/'
    | '/v6/'
    | '/v7/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  V1Route: typeof V1RouteWithChildren
  V2Route: typeof V2RouteWithChildren
  V3Route: typeof V3RouteWithChildren
  V4Route: typeof V4RouteWithChildren
  V5Route: typeof V5RouteWithChildren
  V6Route: typeof V6RouteWithChildren
  V7Route: typeof V7RouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/v7': {
      id: '/v7'
      path: '/v7'
      fullPath: '/v7'
      preLoaderRoute: typeof V7RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v6': {
      id: '/v6'
      path: '/v6'
      fullPath: '/v6'
      preLoaderRoute: typeof V6RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v5': {
      id: '/v5'
      path: '/v5'
      fullPath: '/v5'
      preLoaderRoute: typeof V5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v4': {
      id: '/v4'
      path: '/v4'
      fullPath: '/v4'
      preLoaderRoute: typeof V4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v3': {
      id: '/v3'
      path: '/v3'
      fullPath: '/v3'
      preLoaderRoute: typeof V3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2': {
      id: '/v2'
      path: '/v2'
      fullPath: '/v2'
      preLoaderRoute: typeof V2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1': {
      id: '/v1'
      path: '/v1'
      fullPath: '/v1'
      preLoaderRoute: typeof V1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v7/': {
      id: '/v7/'
      path: '/'
      fullPath: '/v7/'
      preLoaderRoute: typeof V7IndexLazyRouteImport
      parentRoute: typeof V7Route
    }
    '/v6/': {
      id: '/v6/'
      path: '/'
      fullPath: '/v6/'
      preLoaderRoute: typeof V6IndexLazyRouteImport
      parentRoute: typeof V6Route
    }
    '/v5/': {
      id: '/v5/'
      path: '/'
      fullPath: '/v5/'
      preLoaderRoute: typeof V5IndexLazyRouteImport
      parentRoute: typeof V5Route
    }
    '/v4/': {
      id: '/v4/'
      path: '/'
      fullPath: '/v4/'
      preLoaderRoute: typeof V4IndexLazyRouteImport
      parentRoute: typeof V4Route
    }
    '/v3/': {
      id: '/v3/'
      path: '/'
      fullPath: '/v3/'
      preLoaderRoute: typeof V3IndexLazyRouteImport
      parentRoute: typeof V3Route
    }
    '/v2/': {
      id: '/v2/'
      path: '/'
      fullPath: '/v2/'
      preLoaderRoute: typeof V2IndexLazyRouteImport
      parentRoute: typeof V2Route
    }
    '/v1/': {
      id: '/v1/'
      path: '/'
      fullPath: '/v1/'
      preLoaderRoute: typeof V1IndexLazyRouteImport
      parentRoute: typeof V1Route
    }
    '/v7/app': {
      id: '/v7/app'
      path: '/app'
      fullPath: '/v7/app'
      preLoaderRoute: typeof V7AppLazyRouteImport
      parentRoute: typeof V7Route
    }
    '/v6/app': {
      id: '/v6/app'
      path: '/app'
      fullPath: '/v6/app'
      preLoaderRoute: typeof V6AppLazyRouteImport
      parentRoute: typeof V6Route
    }
    '/v5/app': {
      id: '/v5/app'
      path: '/app'
      fullPath: '/v5/app'
      preLoaderRoute: typeof V5AppLazyRouteImport
      parentRoute: typeof V5Route
    }
    '/v4/app': {
      id: '/v4/app'
      path: '/app'
      fullPath: '/v4/app'
      preLoaderRoute: typeof V4AppLazyRouteImport
      parentRoute: typeof V4Route
    }
    '/v3/app': {
      id: '/v3/app'
      path: '/app'
      fullPath: '/v3/app'
      preLoaderRoute: typeof V3AppLazyRouteImport
      parentRoute: typeof V3Route
    }
    '/v2/app': {
      id: '/v2/app'
      path: '/app'
      fullPath: '/v2/app'
      preLoaderRoute: typeof V2AppLazyRouteImport
      parentRoute: typeof V2Route
    }
    '/v1/app': {
      id: '/v1/app'
      path: '/app'
      fullPath: '/v1/app'
      preLoaderRoute: typeof V1AppLazyRouteImport
      parentRoute: typeof V1Route
    }
  }
}

interface V1RouteChildren {
  V1AppLazyRoute: typeof V1AppLazyRoute
  V1IndexLazyRoute: typeof V1IndexLazyRoute
}

const V1RouteChildren: V1RouteChildren = {
  V1AppLazyRoute: V1AppLazyRoute,
  V1IndexLazyRoute: V1IndexLazyRoute,
}

const V1RouteWithChildren = V1Route._addFileChildren(V1RouteChildren)

interface V2RouteChildren {
  V2AppLazyRoute: typeof V2AppLazyRoute
  V2IndexLazyRoute: typeof V2IndexLazyRoute
}

const V2RouteChildren: V2RouteChildren = {
  V2AppLazyRoute: V2AppLazyRoute,
  V2IndexLazyRoute: V2IndexLazyRoute,
}

const V2RouteWithChildren = V2Route._addFileChildren(V2RouteChildren)

interface V3RouteChildren {
  V3AppLazyRoute: typeof V3AppLazyRoute
  V3IndexLazyRoute: typeof V3IndexLazyRoute
}

const V3RouteChildren: V3RouteChildren = {
  V3AppLazyRoute: V3AppLazyRoute,
  V3IndexLazyRoute: V3IndexLazyRoute,
}

const V3RouteWithChildren = V3Route._addFileChildren(V3RouteChildren)

interface V4RouteChildren {
  V4AppLazyRoute: typeof V4AppLazyRoute
  V4IndexLazyRoute: typeof V4IndexLazyRoute
}

const V4RouteChildren: V4RouteChildren = {
  V4AppLazyRoute: V4AppLazyRoute,
  V4IndexLazyRoute: V4IndexLazyRoute,
}

const V4RouteWithChildren = V4Route._addFileChildren(V4RouteChildren)

interface V5RouteChildren {
  V5AppLazyRoute: typeof V5AppLazyRoute
  V5IndexLazyRoute: typeof V5IndexLazyRoute
}

const V5RouteChildren: V5RouteChildren = {
  V5AppLazyRoute: V5AppLazyRoute,
  V5IndexLazyRoute: V5IndexLazyRoute,
}

const V5RouteWithChildren = V5Route._addFileChildren(V5RouteChildren)

interface V6RouteChildren {
  V6AppLazyRoute: typeof V6AppLazyRoute
  V6IndexLazyRoute: typeof V6IndexLazyRoute
}

const V6RouteChildren: V6RouteChildren = {
  V6AppLazyRoute: V6AppLazyRoute,
  V6IndexLazyRoute: V6IndexLazyRoute,
}

const V6RouteWithChildren = V6Route._addFileChildren(V6RouteChildren)

interface V7RouteChildren {
  V7AppLazyRoute: typeof V7AppLazyRoute
  V7IndexLazyRoute: typeof V7IndexLazyRoute
}

const V7RouteChildren: V7RouteChildren = {
  V7AppLazyRoute: V7AppLazyRoute,
  V7IndexLazyRoute: V7IndexLazyRoute,
}

const V7RouteWithChildren = V7Route._addFileChildren(V7RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  V1Route: V1RouteWithChildren,
  V2Route: V2RouteWithChildren,
  V3Route: V3RouteWithChildren,
  V4Route: V4RouteWithChildren,
  V5Route: V5RouteWithChildren,
  V6Route: V6RouteWithChildren,
  V7Route: V7RouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
